# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True, verbose_name='订单id')),
                ('eval_score', models.IntegerField(verbose_name='评价分数')),
                ('eval_content', models.TextField(verbose_name='评价内容')),
                ('eval_date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'db_table': 'evaluate',
            },
        ),
    ]
