# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=128, verbose_name='标题')),
                ('news_content', models.TextField(verbose_name='内容')),
                ('news_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('news_source', models.CharField(max_length=32, verbose_name='新闻来源')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
